# Generated by Django 4.1.3 on 2022-11-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Director',
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('summary', models.TextField(help_text='Sipnosis', max_length=100)),
                ('year', models.DateField(blank=True, null=True)),
                ('author', models.ManyToManyField(to='peliculas.director')),
            ],
        ),
    ]
