# Generated by Django 4.1.3 on 2022-11-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_rename_genre_director_pelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
