# Generated by Django 4.1.3 on 2022-11-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_alter_director_fechanacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='year',
        ),
    ]
