# Generated by Django 4.1.3 on 2022-11-18 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_remove_director_fechanacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='fechaNacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
