# Generated by Django 4.1.3 on 2022-11-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_director_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
