# Generated by Django 4.1.3 on 2022-11-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0006_pelicula_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='author',
            field=models.ManyToManyField(to='peliculas.director'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='summary',
            field=models.TextField(help_text='Sipnosis', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
    ]
